apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-project
  labels:
    app: hospital-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hospital-project
  template:
    metadata:
      labels:
        app: hospital-project
    spec:
      containers:
      - name: hospital-project
        image: sohit007/hospital-project:latest
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: hospital-project
  labels:
    app: hospital-project
spec:
  selector:
    app: hospital-project
  type: NodePort
  ports:
    - nodePort: 31233 
      port: 80
      targetPort: 8082

